name: test_task
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  elementary: ^1.2.0
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  surf_lint_rules: ^1.5.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.8

flutter:
  uses-material-design: true