name: simpledo
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  elementary: ^1.2.0

  feature_core: &feature_version ^1.0.2
  feature_flutter: *feature_version
  feature_source_firebase: *feature_version
  feature_source_retain: *feature_version
  firebase_remote_config: ^2.0.0
  shared_preferences: ^2.0.13

  flutter:
    sdk: flutter

  hive: ^2.1.0
  hive_flutter: ^1.1.0
  mockito: ^5.1.0
  uuid: ^3.0.6

  firebase_analytics: ^9.1.7

dev_dependencies:
  build_runner: ^2.1.8
  flutter_launcher_icons: 0.9.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  surf_lint_rules: ^1.5.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "icon/launcher_icon.png"
  android: true
  ios: true
  # optionally, as transparency is not allowed on app store
  # remove_alpha_ios: true